In [1]:
!pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import numpy as np

In [3]:
some_list = [1,2,3,4]
type(some_list)

list

In [4]:
ones_array = np.ones(5)
ones_array

array([1., 1., 1., 1., 1.])

In [5]:
range_array = np.arange(8)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
reshaped_array = range_array.reshape(2,4)
reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])